Frozen Hell 1.8
CitadelCore/DescentPacks pull request #138
Opened 2020-09-06 17:08 UTC by skyem123

2020-09-06 21:03 UTC, NickStalburg requested changes

2020-09-06 21:03 UTC, NickStalburg commented on descentfrozenhell/config/immersiverailroading.cfg
> +        # Clear blocsk in creative mode when placing tracks
Fix the spelling of 'blocks'

2020-09-07 18:06 UTC, NickStalburg approved these changes
Yes all looks good.

2020-09-07 18:06 UTC, skyem123 reviewed
All done!

2020-09-07 18:09 UTC, ThePiGuy24 approved these changes
it looks like it probably wont break everything, good enough.

2020-09-07 18:09 UTC, CitadelCore approved these changes

2020-09-07 18:10 UTC, CitadelCore commented
ISC approved, ready for merge

2020-09-07 18:12 UTC, skyem123 commented
Once it passes CI, I will merge it.

2020-09-07 18:17 UTC, merged